# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/saimonmoore.org
cert = /etc/letsencrypt/live/saimonmoore.org/cert.pem
privkey = /etc/letsencrypt/live/saimonmoore.org/privkey.pem
chain = /etc/letsencrypt/live/saimonmoore.org/chain.pem
fullchain = /etc/letsencrypt/live/saimonmoore.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = certbot-plugin-gandi:dns
certbot_plugin_gandi:dns_credentials = /etc/letsencrypt/gandi.ini
account = redacted
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory