[supervisord]
  nodaemon=true

[unix_http_server]
  file=/var/run/supervisor.sock
  chmod=0700

[supervisorctl]
  serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:nginx]
  command=/usr/sbin/nginx -g 'daemon off;'
  autostart=true
  autorestart=true
  startretries=3
  stopsignal=TERM
  stopasgroup=true
  killasgroup=true
  stdout_logfile=/dev/stdout
  stdout_logfile_maxbytes=0
  stderr_logfile=/dev/stderr
  stderr_logfile_maxbytes=0

[program:dht]
  command= /app/startServers.sh relay
  autostart=true
  autorestart=true
  startretries=3
  stopsignal=TERM
  stopasgroup=true
  killasgroup=true
  stdout_logfile=/dev/stdout
  stdout_logfile_maxbytes=0
  stderr_logfile=/dev/stderr
  stderr_logfile_maxbytes=0

[program:http]
  command= /app/startServers.sh web
  autostart=true
  autorestart=true
  startretries=3
  stopsignal=TERM
  stopasgroup=true
  killasgroup=true
  stdout_logfile=/dev/stdout
  stdout_logfile_maxbytes=0
  stderr_logfile=/dev/stderr
  stderr_logfile_maxbytes=0

# [eventlistener:check_http]
# command=/usr/local/bin/supervisor_http_check -n check_app -N http -u /ai/health -t 30 -r 3 -p 3000
# events=TICK_60

# [eventlistener:check_dht]
# command=/bin/sh -c "nc -z localhost 49443 || exit 1"
# events=TICK_60
